mov $r1, @r3
; hello this is comment

mcro $%^&
prn -1
endmcro sometext

mcro prn
ok
endmcro 

endmcro: hey

thisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylonglinethisisveryverylongline

prn 
m1